### ISSUE TITLE
Disable option based on row value

### ISSUE THREAD

**Issue by APEXGru** [Dani3lSun/apex-plugin-extend_ig_menu#1]
### Expected behavior
Disable an option based on a column value (similar to the Delete Row using the "Allowed operations" setting). So for one row it may be enabled, for the next it may be disabled.

### Actual behavior
An option is initially disabled based on a Page Item value. So it applies to all records.

### Steps to reproduce the issue
n/a

### APEX version (4.2.6 / 5.0.3)
5.1.2

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
n/a

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
n/a

**Comment by Dani3lSun** [comment]
Hey @APEXGru 
nice enhancement request!
I will update this issue if I thought about it or have some solution ready...I´m completely packed with work so this might be somewhen next week...

**Comment by APEXGru** [comment]
Hi Daniel,

So 28 days ago you said "somewhere next week....". 
What is the current ETA? 

Keep up the good work!  ;-)

Cheers
Roel a.k.a. APEXGru

**Comment by Dani3lSun** [comment]
Hey Roel,

yeah sorry for the delay...
But I started with it 2 days ago, so I hope I could finish it by the weekend! 

I´ll keep you updated! ;)

**Comment by Dani3lSun** [comment]
Hey Roel,

just to let you know, a new version is ready and it is now possible to create hide & disable conditions column based...
https://github.com/Dani3lSun/apex-plugin-extend_ig_menu/releases/tag/v1.1.0
I completely reviewed the code and replaced the JQuery methods (plugin was released just a couple of weeks after 5.1) now with IG native functions so should be way more future proof...

Let me know if it works well for you! ;)

![grid_menu_plugin](https://user-images.githubusercontent.com/698942/31553744-bc1335da-b03b-11e7-8b47-06a452a87d66.gif)

**Comment by APEXGru** [comment]
Yeah, I saw that. Thanks!
But I won’t be at the client site for the next two weeks (first SIOUG and HROUG then holiday). But I’ll let you know if it works as expected...

Met vriendelijke groet / With kind regards,
Roel Hartman

**Comment by Dani3lSun** [comment]
Yeah, don´t hurry...Have fun at these conferences! Weather should be nice! ;)
