### ISSUE TITLE
Menu Extensions disappear when you switch from (first) report to another

### ISSUE THREAD

**Issue by APEXGru** [Dani3lSun/apex-plugin-extend_ig_menu#2]
### Expected behavior
Menu Extensions should still be there

### Actual behavior
If you select another report from the available Reports (either Public or Private), the extensions disappear. On total page reload they re-appear.

### Steps to reproduce the issue
Go to your demo page, check the Menu Extensions. Select one of the other predefined reports and check again.

### APEX version (4.2.6 / 5.0.3)
apex.oracle.com

**Comment by Dani3lSun** [comment]
I will have a look! Thanks for reporting ;)

**Comment by Dani3lSun** [comment]
Bug should be fixed now...The menu entries are now recreated if the grid view changes...

**Comment by APEXGru** [comment]
Thanks. I’ll be at the customer’s site on Monday and update the plugin!

Met vriendelijke groet / With kind regards,
Roel Hartman

**Comment by APEXGru** [comment]
Better, but not quite there yet ...
In report 1, check out a record / menu that has 1 enabled and 1 disabled option.
Switch to report 2, check out a record / menu that should have 2 enabled (or 2 disabled) options ... it doesn't as it still has (and keeps!) the setting as you last checked in report 1. 
Switching back to report 1 shows the same setting for every record now.

Tested in Chrome 42 and FF 45(I know it is old - but working at the MoD and they don't download the latest and greatest versions immediately).

**Comment by Dani3lSun** [comment]
Hey @APEXGru 
I´m not completely sure how you do this...Would be nice if you can supply some screencast or animated GIF to see your problem in action?!
Thanks!

**Comment by APEXGru** [comment]
Hi Daniel,

See this recording (https://we.tl/n8lvVQUirJ). The first time - immediately after rendering - the enable/disable runs fine. Then I switch to another report and back to the primary. And now the enable/disable setting is like the last one I used (in this case "enable"),
Hope this clears the fog

APEXGru.

**Comment by Dani3lSun** [comment]
Thanks @APEXGru !
Now it´s much clearer & I can reproduce the behavior in my env...
I´ll keep you updated when I have something ready!

**Comment by Dani3lSun** [comment]
Seems that this problem is fixed now...Changed the event handlers to be more dynamic, e.g listen on parent elements for the dyn. created elements. In APEX speech I would say: Event Scope = Dynamic :)
Here are the important changes:
https://github.com/Dani3lSun/apex-plugin-extend_ig_menu/commit/7ca0feb2a2bd4af1b141442e218f603d08b74ae9#diff-0f1904dbd6b5d9b1ca90843f2225b741

And here´s the new release:
https://github.com/Dani3lSun/apex-plugin-extend_ig_menu/releases/tag/v1.1.3
