### ISSUE TITLE
Execute Column link or Redirect Page

### ISSUE THREAD

**Issue by Adamramroop** [Dani3lSun/apex-plugin-extend_ig_menu#3]
Is it possible to use this Plugin to execute a link in the row (like a redirect to another page while passing certain items).

Currently this is not an option unless i am missing it.

Using ApEX 5.1

Thank you for this AWESOME Plugin.

**Comment by Dani3lSun** [comment]
Hi @Adamramroop 

this is not currently implemented in the plugin itself, it only returns the PK value of the row.
But you´re able to do it by your own via a seperate Dynamic Action.

First Dynamic Action:
1) New DA with on change event of the hidden item which holds the PK value
2) Execute PL/SQL Code to get a proper URL, e.g with apex_page.get_url
https://docs.oracle.com/database/apex-5.1/AEAPI/GET_URL-Function.htm#AEAPI30190
3) Return this URL into another hidden item

Second Dynamic Action:
1) New DA with on change event of hidden item which holds the URL
2) Execute JavaScript Code:
```
// get url of hidden Item
var url = $v('P1_YOUR_URL_ITEM');

// if target is not a modal page, do a normal redirect
if (url.indexOf('apex.navigation.dialog') == -1) {
  url = 'apex.navigation.redirect("' + url + '");';
}

// create a function using given url and call it
try {
  var urlFnc = new Function(url)();
  urlFnc();
} catch (err) {
  console.log(err);
}
```

Maybe I will integrate such a feature directly into the plugin if I have some free time, so I mark this issue as enhancement idea...

Hope this helps!
Daniel

**Comment by Adamramroop** [comment]
Thank you!

I will try this out this morning and get check back in with you.

New to Developer role and I’m loving it!

Thanks for all the cool plugins ( great website too)

Adam
